#!/bin/bash
sudo apt-get install acl
sudo apt-get install attr
sudo apt-get install autoconf
sudo apt-get install automake
sudo apt-get install bash
sudo apt-get install bc
sudo apt-get install binutils
sudo apt-get install bison
sudo apt-get install bzip2
sudo apt-get install check
sudo apt-get install coreutils
sudo apt-get install dejagnu
sudo apt-get install diffutils
sudo apt-get install e2fsprongs
sudo apt-get install elfutils
sudo apt-get install expat
sudo apt-get install expect
sudo apt-get install file
sudo apt-get install findutils
sudo apt-get install flex
sudo apt-get install flit-core
sudo apt-get install gawk
sudo apt-get install gcc
sudo apt-get install gdbm
sudo apt-get install gettext
sudo apt-get install glibc
sudo apt-get install gmp
sudo apt-get install gperf
sudo apt-get install groff
sudo apt-get install grub
sudo apt-get install gzip
sudo apt-get install iana-etc
sudo apt-get install inetutils
sudo apt-get install intltool
sudo apt-get install iproute2
sudo apt-get install jinja2
sudo apt-get install kdb
sudo apt-get install kmod
sudo apt-get install lfs-bootscripts
sudo apt-get install libcap
sudo apt-get install libffi
sudo apt-get install libpipeline
sudo apt-get install libtool
sudo apt-get install libxcrypt
sudo apt-get install m4
sudo apt-get install make
sudo apt-get install man-db
sudo apt-get install man-pages
sudo apt-get install markupsafe
sudo apt-get install meson
sudo apt-get install mpc
sudo apt-get install mpfr
sudo apt-get install ncurses
sudo apt-get install ninja
sudo apt-get install openssl
sudo apt-get install patch
sudo apt-get install perl
sudo apt-get install pkgconf
sudo apt-get install procps
sudo apt-get install psmisc
sudo apt-get install readline
sudo apt-get install sed
sudo apt-get install shadow
sudo apt-get install sysklogd
sudo apt-get install systemd
sudo apt-get install sysvinit
sudo apt-get install tar
sudo apt-get install tcl
sudo apt-get install texinfo
sudo apt-get install time-zones
sudo apt-get install util-linux
sudo apt-get install wheel
sudo apt-get install xml
sudo apt-get install xz
sudo apt-get install zlib
